def _preset(
    version_name,
    description,
    *,
    use_custom_scheduler,
    default_scheduler_type,
    use_adaptive_tgs,
    use_anchorflow,
    use_soft_mask=False,
    soft_mask_threshold_scale=1.5,
    soft_mask_sharpness=12.0,
    soft_mask_min=0.10,
    use_late_boost=False,
    late_boost_gain=0.30,
    use_source_velocity=False,
    source_velocity_scale=1.0,
    use_latent_blend=False,
    latent_blend_strength=0.9,
    latent_mask_sharpness=18.0,
    latent_mask_percentile=0.96,
    use_local_aux_blend=False,
):
    return {
        "version_name": version_name,
        "description": description,
        "use_custom_scheduler": use_custom_scheduler,
        "default_scheduler_type": default_scheduler_type,
        "use_adaptive_tgs": use_adaptive_tgs,
        "use_anchorflow": use_anchorflow,
        "use_soft_mask": use_soft_mask,
        "soft_mask_threshold_scale": soft_mask_threshold_scale,
        "soft_mask_sharpness": soft_mask_sharpness,
        "soft_mask_min": soft_mask_min,
        "use_late_boost": use_late_boost,
        "late_boost_gain": late_boost_gain,
        "use_source_velocity": use_source_velocity,
        "source_velocity_scale": source_velocity_scale,
        "use_latent_blend": use_latent_blend,
        "latent_blend_strength": latent_blend_strength,
        "latent_mask_sharpness": latent_mask_sharpness,
        "latent_mask_percentile": latent_mask_percentile,
        "use_local_aux_blend": use_local_aux_blend,
    }


PRESET_CONFIGS = {
    "v1_clean": _preset(
        "v1_clean",
        "纯干净版本：默认原生 scheduler，无 adaptive tar guidance，无 anchor。",
        use_custom_scheduler=False,
        default_scheduler_type="default",
        use_adaptive_tgs=False,
        use_anchorflow=False,
    ),
    "v2_scheduler": _preset(
        "v2_scheduler",
        "在 v1 基础上加入自定义噪声/σ调度方案（默认 default_slower）。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=False,
        use_anchorflow=False,
    ),
    "v3_adaptive": _preset(
        "v3_adaptive",
        "在 v1 基础上加入基于视角的 tar guidance 自适应系数。",
        use_custom_scheduler=False,
        default_scheduler_type="default",
        use_adaptive_tgs=True,
        use_anchorflow=False,
    ),
    "v4_anchor": _preset(
        "v4_anchor",
        "在 v1 基础上加入 anchor，不加入自定义调度。",
        use_custom_scheduler=False,
        default_scheduler_type="default",
        use_adaptive_tgs=False,
        use_anchorflow=True,
    ),
    "v5_scheduler_adaptive": _preset(
        "v5_scheduler_adaptive",
        "在 v2 基础上加入基于视角的 tar guidance 自适应系数。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=False,
    ),
    "v6_full": _preset(
        "v6_full",
        "最全版本：v5 基础上再加入 anchor。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=True,
    ),
    "v1_clean_new": _preset(
        "v1_clean_new",
        "v1_clean + ColorC1 的末端潜空间背景回拉。",
        use_custom_scheduler=False,
        default_scheduler_type="default",
        use_adaptive_tgs=False,
        use_anchorflow=False,
        use_latent_blend=True,
    ),
    "v2_scheduler_new": _preset(
        "v2_scheduler_new",
        "v2_scheduler + ColorC1 的末端潜空间背景回拉。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=False,
        use_anchorflow=False,
        use_latent_blend=True,
    ),
    "v3_adaptive_new": _preset(
        "v3_adaptive_new",
        "v3_adaptive + ColorC1 的末端潜空间背景回拉。",
        use_custom_scheduler=False,
        default_scheduler_type="default",
        use_adaptive_tgs=True,
        use_anchorflow=False,
        use_latent_blend=True,
    ),
    "v4_anchor_new": _preset(
        "v4_anchor_new",
        "v4_anchor + ColorC1 的末端潜空间背景回拉。",
        use_custom_scheduler=False,
        default_scheduler_type="default",
        use_adaptive_tgs=False,
        use_anchorflow=True,
        use_latent_blend=True,
    ),
    "v5_scheduler_adaptive_new": _preset(
        "v5_scheduler_adaptive_new",
        "v5_scheduler_adaptive + ColorC1 的末端潜空间背景回拉。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=False,
        use_latent_blend=True,
    ),
    "v6_full_new": _preset(
        "v6_full_new",
        "v6_full + ColorC1 的末端潜空间背景回拉。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=True,
        use_latent_blend=True,
    ),
    "v6_exp_softmask": _preset(
        "v6_exp_softmask",
        "v6_full + ColorC1 的逐步软掩码编辑门控。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=True,
        use_soft_mask=True,
    ),
    "v6_exp_lateboost": _preset(
        "v6_exp_lateboost",
        "v6_full + ColorC1 的后期编辑增强（late boost）。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=True,
        use_late_boost=True,
    ),
    "v6_exp_sourcevel": _preset(
        "v6_exp_sourcevel",
        "v6_full + ColorC1 的 source velocity 残差保真项。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=True,
        use_source_velocity=True,
    ),
    "v6_exp_latentblend": _preset(
        "v6_exp_latentblend",
        "v6_full + ColorC1 的末端潜空间背景拉回。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=True,
        use_latent_blend=True,
    ),
    "v6_exp_localblend": _preset(
        "v6_exp_localblend",
        "v6_full + ColorC1 的局部辅助引导软融合，替代硬 ownership 切分。",
        use_custom_scheduler=True,
        default_scheduler_type="default_slower",
        use_adaptive_tgs=True,
        use_anchorflow=True,
        use_local_aux_blend=True,
    ),
}


CUSTOM_SCHEDULER_CHOICES = [
    "default",
    "medium",
    "linear",
    "slower",
    "cubic_fidelity",
    "default_slower",
]
